"""empty message

Revision ID: 2779009f1ed1
Revises: 334fd120766c
Create Date: 2020-10-04 23:55:37.982348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2779009f1ed1'
down_revision = '334fd120766c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('users', sa.String(length=8000), nullable=True))
    op.drop_constraint('boards_user_id_fkey', 'boards', type_='foreignkey')
    op.create_foreign_key(None, 'boards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('custom_nodes', 'board_id',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('custom_nodes', 'user_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.drop_constraint('custom_nodes_user_id_fkey', 'custom_nodes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('custom_nodes_user_id_fkey', 'custom_nodes', 'users', ['user_id'], ['id'])
    op.alter_column('custom_nodes', 'user_id',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('custom_nodes', 'board_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.create_foreign_key('boards_user_id_fkey', 'boards', 'users', ['user_id'], ['id'])
    op.drop_column('boards', 'users')
    # ### end Alembic commands ###
