"""empty message

Revision ID: 334fd120766c
Revises: ee5266ceda6a
Create Date: 2020-10-04 19:13:40.436634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334fd120766c'
down_revision = 'ee5266ceda6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'confirmed_on',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'confirmed_on',
               existing_type=sa.String(length=64),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
