"""empty message

Revision ID: 3e3d171ecf12
Revises: c7a485f18756
Create Date: 2020-06-20 22:37:03.656121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3d171ecf12'
down_revision = 'c7a485f18756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_nodes', 'analisis_params',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=100000),
               existing_nullable=True)
    op.alter_column('custom_nodes', 'api_url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_nodes', 'api_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('custom_nodes', 'analisis_params',
               existing_type=sa.String(length=100000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###
