"""empty message

Revision ID: a196789c0b20
Revises: ddd9cfd7eff9
Create Date: 2020-07-14 22:26:52.454429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a196789c0b20'
down_revision = 'ddd9cfd7eff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'nodes',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.String(length=100000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'nodes',
               existing_type=sa.String(length=100000),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###
