"""empty message

Revision ID: c7a485f18756
Revises: 
Create Date: 2020-06-20 22:15:25.354791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a485f18756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_nodes', 'analisis_params',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=100000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_nodes', 'analisis_params',
               existing_type=sa.String(length=100000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###
