"""empty message

Revision ID: f7f2477eac27
Revises: 2eeb0358560e
Create Date: 2020-11-11 13:59:31.171857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f2477eac27'
down_revision = '2eeb0358560e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
